TstCad/Models/ErrorViewModel.cs
using System;

namespace TstCad.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TstCad/Models/PessoaModel.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace TstCad.Models
{
    public class PessoaModel
    {
        // Campos ou atributos da classe (campos do banco de dados):
        [DisplayName("ID")]
        public int PessoaId { get; set; }
        [DisplayName("Nome")]
        public string NomePessoa { get; set; }
        [DisplayName("E-Mail")]
        public string EmailPessoa { get; set; }
        [DisplayName("Telefone")]
        public string TelefonePessoa { get; set; }

        // Criar CONSTANTE para conexão com banco:
        readonly string connectionString = @"Data Source=DESKTOP-U84PPK5\SQLEXPRESS;Initial Catalog=MeuBD;Integrated Security=True";

        public DataTable Listar()
        {
            DataTable tblPessoa = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                SqlDataAdapter sqlDA = new SqlDataAdapter("SELECT * FROM tb_Pessoa", sqlCon);
                sqlDA.Fill(tblPessoa);
            }
            return tblPessoa;
        }
        public void Salvar()
        {
            // Cria a conexão com BD:
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                // Abre a conexão com BD:
                sqlCon.Open();
                // Instrução SQL para execução no BD:
                SqlCommand sqlCmd = new SqlCommand(
                    "INSERT INTO tb_Pessoa VALUES(@NomePessoa, @EmailPessoa, @TelefonePessoa)", sqlCon
                    );
                // Atribuir dados aos caampos (ou parâmetros da instrução SQL):
                sqlCmd.Parameters.AddWithValue("@NomePessoa", NomePessoa);
                sqlCmd.Parameters.AddWithValue("@EmailPessoa", EmailPessoa);
                sqlCmd.Parameters.AddWithValue("@TelefonePessoa", TelefonePessoa);
                // Executar o comando no SQL:
                sqlCmd.ExecuteNonQuery();
            }
        }
    }
}

TstCad/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TstCad.Models;

namespace TstCad.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Página de testes - AAS";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TstCad/Controllers/PessoaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TstCad.Models;

namespace TstCad.Controllers
{
    public class PessoaController : Controller
    {
        // GET: Pessoa
        [HttpGet]
        public ActionResult Index()
        {
            PessoaModel pModel = new PessoaModel();
            return View(pModel.Listar());
        }

        // GET: Pessoa/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Pessoa/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View(new PessoaModel());
        }

        // POST: Pessoa/Create
        [HttpPost]
        public ActionResult Create(PessoaModel pModel)
        {
            pModel.Salvar();
            return RedirectToAction("Index");
        }

        // GET: Pessoa/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pessoa/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pessoa/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Pessoa/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TstCad/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Sobre";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Esta página / aplicação é uma introdução ao desenvolvimento de Aplicações Web com a tecnologia ASP.NET, utilizando a linguagem c#.</p>

TstCad/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TstCad/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="col-md-12">
    <br />
    <h2>Seja bem vindo a esta página</h2>
</div>

TstCad/Views/Pessoa/Create.cshtml
@model TstCad.Models.PessoaModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>PessoaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PessoaId" class="control-label"></label>
                <input asp-for="PessoaId" class="form-control" />
                <span asp-validation-for="PessoaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomePessoa" class="control-label"></label>
                <input asp-for="NomePessoa" class="form-control" />
                <span asp-validation-for="NomePessoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailPessoa" class="control-label"></label>
                <input asp-for="EmailPessoa" class="form-control" />
                <span asp-validation-for="EmailPessoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelefonePessoa" class="control-label"></label>
                <input asp-for="TelefonePessoa" class="form-control" />
                <span asp-validation-for="TelefonePessoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TstCad/Views/Pessoa/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h3>Cadastro de Pessoas</h3>
<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>E-Mail</th>
        <th>Telefone</th>
    </tr>
    @for (int i = 0; i < Model.Rows.Count; i++)
    {
        <tr>
            <td>@Model.Rows[i][0]</td>
            <td>@Model.Rows[i][1]</td>
            <td>@Model.Rows[i][2]</td>
            <td>@Model.Rows[i][3]</td>
        </tr>
    }
</table>
<a href="@Url.Action("Create", "Pessoa")">Novo</a>

TstCad/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TstCad</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TstCad</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicial</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Sobre</a></li>
                    <li><a asp-area="" asp-controller="Pessoa" asp-action="Index">Cadastro</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - TstCad - AAS</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>